/**
 * @see https://docs.singlestore.com/managed-service/en/reference/data-api/data-api-data-type-conversion.html
 */
export enum SingleStoreDataType {
  BigInt = 'BIGINT',
  Binary = 'BINARY',
  Bit = 'BIT',
  Blob = 'BLOB',
  Bool = 'BOOL',
  Boolean = 'BOOLEAN',
  Char = 'CHAR',
  Date = 'DATE',
  Datetime = 'DATETIME',
  Decimal = 'DECIMAL',
  Double = 'DOUBLE',
  Enum = 'ENUM',
  Float = 'FLOAT',
  Geography = 'GEOGRAPHY',
  GeographyPoint = 'GEOGRAPHYPOINT',
  Int = 'INT',
  Integer = 'INTEGER',
  Json = 'JSON',
  LongBlob = 'LONGBLOB',
  LongText = 'LONGTEXT',
  MediumBlob = 'MEDIUMBLOB',
  MediumInt = 'MEDIUMINT',
  MediumText = 'MEDIUMTEXT',
  Set = 'SET',
  SmallInt = 'SMALLINT',
  Text = 'TEXT',
  Time = 'TIME',
  Timestamp = 'TIMESTAMP',
  TinyBlob = 'TINYBLOB',
  TinyInt = 'TINYINT',
  TinyText = 'TINYTEXT',
  Varbinary = 'VARBINARY',
  Varchar = 'VARCHAR',
  Year = 'YEAR',
}
